spring:
  application:
    name: hyungchul-backend-spring

  # 기본 프로필 설정
  profiles:
    active: dev  # 기본값으로 dev 프로필 사용

  servlet:
    multipart:
      max-file-size: 10MB       # 단일 파일 최대 크기
      max-request-size: 100MB   # 전체 요청 최대 크기 (모든 파일 및 폼 데이터 포함)

server:
  port: 8080
  servlet:
    context-path: /api

jwt:
  secret: c2RmYmFzZGtnamJzYWRuZndscXB6bWduYmVs
  access-token-expiration-ms: 3600000 # 예: 1시간 (밀리초)
  refresh-token-expiration-ms: 604800000 # 예: 7일 (밀리초)
  token-prefix: Bearer
  header-string: Authorization

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

logging:
  level:
    org.springframework.web.cors: DEBUG